### ISSUE TITLE
install-issue

### ISSUE THREAD

**Issue by Alesak80** [jakubonty/weather_station_mqtt#5]
Hi, I cannot install this addon. HA Supervisor says:

21-08-20 13:24:01 INFO (SyncWorker_2) [supervisor.docker.addon] Starting build for local/amd64-addon-weather_station_mqtt:0.1
21-08-20 13:24:14 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build local/amd64-addon-weather_station_mqtt:0.1: The command '/bin/ash -o pipefail -c apk add --no-cache nodejs-npm' returned a non-zero code: 1
21-08-20 13:24:14 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log: 
Step 1/18 : ARG BUILD_FROM
Step 2/18 : FROM $BUILD_FROM
 ---> 8fc812b16962
Step 3/18 : ENV LANG C.UTF-8
 ---> Using cache
 ---> e2c9e2f0b997
Step 4/18 : COPY data/run.sh /
 ---> Using cache
 ---> 0d6b5b721895
Step 5/18 : COPY maserver/* /
 ---> Using cache
 ---> 3b5f3036d0d4
Step 6/18 : RUN apk add --no-cache nodejs-npm
 ---> Running in 7e7575000e73
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:

  nodejs-npm (no such package):
    required by: world[nodejs-npm]
Removing intermediate container 7e7575000e73

**Comment by jakubonty** [comment]
Hello,
thank you for reporting.

There was changed package name, I updated Docker file, with last version it should work.
