### ISSUE TITLE
Unable to install add-on

### ISSUE THREAD

**Issue by iTzOle** [jakubonty/weather_station_mqtt#6]
After copying the files to the designated folder and trying to install I recieve follwing error message:

"The command '/bin/ash -o pipefail -c apk add --no-cache nodejs-npm' returned a non-zero code: 1"

System is a RasPi3 running Homebridge OS. Please let me know what further information you might require to solve the problem.

Best regards
Ole

**Comment by jakubonty** [comment]
Hello,
thank you for reporting.

There was changed package name, I updated Docker file, with last version it should work.
